services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: building_s3_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: >
      server
      --address ":9000"
      --console-address ":9001"
      /data-s3
    volumes:
      - data-s3:/data-s3
    expose:
      - "9000"
      - "9001"

  nginx-s3:
    build:
      context: nginx-s3
      dockerfile: Dockerfile
    container_name: building_s3_minio-nginx-s3
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "8080:80"

  nginx-console:
    build:
      context: nginx-console
      dockerfile: Dockerfile
    container_name: building_s3_minio-nginx-console
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "8081:80"

volumes:
  data-s3:
